name: Run Web Test for Orange HRM Demo UI
on:
    push:
        branches:
            - master
        pull_request:
            types:[opened,synchronize]
        issues:
            types:
                - opened
                - labeled
    workflow_dispatch:

jobs:
    build:
        run-web-test:
            runs-on: ubuntu-latest
            steps:
                -   name: Pull the project into the machine
                    uses: actions/checkout/@v2

                -   name: setup JDK v11
                    uses: actions/setup-java@v1
                    with:
                        java-version: 11

                -   name: Run Unit Test
                    run: mvn clean test